/* Generated by re2c 0.16 on Fri Aug 26 01:19:13 2016 */
#line 1 "request_scanners.re"

#include <stdio.h>
#include <string.h>

#define YYCTYPE char

struct lex_ctx {
    unsigned char * buf;
    unsigned char * tok;
    unsigned char * cur;
    unsigned char * mar;
    unsigned char * lim;
};

static int lex_str(struct lex_ctx *in, unsigned char q)
{
    printf("%c", q);
    unsigned char u = q;
    for (;;printf("%c", u)) {
        in->tok = in->cur;
        
#line 25 "request_scanners.c"
{
	YYCTYPE yych;
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy4;
	case '\\':	goto yy6;
	default:	goto yy2;
	}
yy2:
	++in->cur;
#line 28 "request_scanners.re"
	{ u = *in->tok; if (u == q) break; continue; }
#line 38 "request_scanners.c"
yy4:
	++in->cur;
yy5:
#line 27 "request_scanners.re"
	{ return 0; }
#line 44 "request_scanners.c"
yy6:
	yych = *++in->cur;
	switch (yych) {
	case '"':	goto yy7;
	case '\'':	goto yy9;
	case '?':	goto yy11;
	case '\\':	goto yy13;
	case 'a':	goto yy15;
	case 'b':	goto yy17;
	case 'f':	goto yy19;
	case 'n':	goto yy21;
	case 'r':	goto yy23;
	case 't':	goto yy25;
	case 'v':	goto yy27;
	default:	goto yy5;
	}
yy7:
	++in->cur;
#line 38 "request_scanners.re"
	{ u = '"';  continue; }
#line 65 "request_scanners.c"
yy9:
	++in->cur;
#line 37 "request_scanners.re"
	{ u = '\''; continue; }
#line 70 "request_scanners.c"
yy11:
	++in->cur;
#line 39 "request_scanners.re"
	{ u = '?';  continue; }
#line 75 "request_scanners.c"
yy13:
	++in->cur;
#line 36 "request_scanners.re"
	{ u = '\\'; continue; }
#line 80 "request_scanners.c"
yy15:
	++in->cur;
#line 29 "request_scanners.re"
	{ u = '\a'; continue; }
#line 85 "request_scanners.c"
yy17:
	++in->cur;
#line 30 "request_scanners.re"
	{ u = '\b'; continue; }
#line 90 "request_scanners.c"
yy19:
	++in->cur;
#line 31 "request_scanners.re"
	{ u = '\f'; continue; }
#line 95 "request_scanners.c"
yy21:
	++in->cur;
#line 32 "request_scanners.re"
	{ u = '\n'; continue; }
#line 100 "request_scanners.c"
yy23:
	++in->cur;
#line 33 "request_scanners.re"
	{ u = '\r'; continue; }
#line 105 "request_scanners.c"
yy25:
	++in->cur;
#line 34 "request_scanners.re"
	{ u = '\t'; continue; }
#line 110 "request_scanners.c"
yy27:
	++in->cur;
#line 35 "request_scanners.re"
	{ u = '\v'; continue; }
#line 115 "request_scanners.c"
}
#line 40 "request_scanners.re"

    }
    printf("%c", q);
    return 1;
}

int php_request_digest_lex(const char * str, size_t len)
{
    struct lex_ctx _in = {
        str,
        str,
        str,
        0,
        str + len
    };
    struct lex_ctx * in = &_in;

    for (;;) {
        in->tok = in->cur;
        
#line 138 "request_scanners.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	yych = *in->cur;
	switch (yych) {
	case 0x00:	goto yy31;
	case '\t':
	case '\n':
	case '\v':
	case '\r':
	case ' ':	goto yy35;
	case '"':	goto yy38;
	case '\'':	goto yy40;
	case ',':	goto yy41;
	case '/':	goto yy43;
	case '=':	goto yy44;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	case 'L':	goto yy49;
	case 'c':	goto yy50;
	case 'n':	goto yy51;
	case 'q':	goto yy52;
	case 'r':	goto yy53;
	case 'u':	goto yy54;
	default:	goto yy33;
	}
yy31:
	++in->cur;
#line 68 "request_scanners.re"
	{ return in->lim == in->tok; }
#line 214 "request_scanners.c"
yy33:
	++in->cur;
yy34:
#line 67 "request_scanners.re"
	{ return 0; printf("sigh %c\n", *in->tok); continue; return 0; }
#line 220 "request_scanners.c"
yy35:
	yyaccept = 0;
	in->mar = ++in->cur;
	yych = *in->cur;
	switch (yych) {
	case '\t':
	case '\n':
	case '\v':
	case '\r':
	case ' ':	goto yy35;
	case '/':	goto yy55;
	default:	goto yy37;
	}
yy37:
#line 74 "request_scanners.re"
	{ printf(" "); continue; }
#line 237 "request_scanners.c"
yy38:
	++in->cur;
yy39:
#line 77 "request_scanners.re"
	{ if (!lex_str(in, *(in->cur - 1))) return 0; continue; }
#line 243 "request_scanners.c"
yy40:
	yych = *++in->cur;
	switch (yych) {
	case '\'':	goto yy57;
	default:	goto yy39;
	}
yy41:
	++in->cur;
#line 90 "request_scanners.re"
	{ printf(",");     continue; }
#line 254 "request_scanners.c"
yy43:
	yyaccept = 1;
	yych = *(in->mar = ++in->cur);
	switch (yych) {
	case '*':	goto yy59;
	case '/':	goto yy61;
	default:	goto yy34;
	}
yy44:
	++in->cur;
#line 89 "request_scanners.re"
	{ printf("=");      continue; }
#line 267 "request_scanners.c"
yy46:
	++in->cur;
	yych = *in->cur;
yy47:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy48;
	}
yy48:
#line 94 "request_scanners.re"
	{ printf("%.*s", in->cur - in->tok, in->tok); continue; }
#line 341 "request_scanners.c"
yy49:
	yych = *++in->cur;
	switch (yych) {
	case '"':	goto yy38;
	case '\'':	goto yy40;
	default:	goto yy47;
	}
yy50:
	yych = *++in->cur;
	switch (yych) {
	case 'n':	goto yy63;
	default:	goto yy47;
	}
yy51:
	yych = *++in->cur;
	switch (yych) {
	case 'c':	goto yy64;
	case 'o':	goto yy66;
	default:	goto yy47;
	}
yy52:
	yych = *++in->cur;
	switch (yych) {
	case 'o':	goto yy67;
	default:	goto yy47;
	}
yy53:
	yych = *++in->cur;
	switch (yych) {
	case 'e':	goto yy68;
	default:	goto yy47;
	}
yy54:
	yych = *++in->cur;
	switch (yych) {
	case 'r':	goto yy69;
	case 's':	goto yy70;
	default:	goto yy47;
	}
yy55:
	++in->cur;
	yych = *in->cur;
	switch (yych) {
	case '*':	goto yy59;
	case '/':	goto yy61;
	default:	goto yy56;
	}
yy56:
	in->cur = in->mar;
	if (yyaccept == 0) {
		goto yy37;
	} else {
		goto yy34;
	}
yy57:
	++in->cur;
#line 78 "request_scanners.re"
	{ return 0; }
#line 400 "request_scanners.c"
yy59:
	++in->cur;
	yych = *in->cur;
	switch (yych) {
	case '*':	goto yy71;
	default:	goto yy59;
	}
yy61:
	++in->cur;
	yych = *in->cur;
	switch (yych) {
	case '\n':	goto yy35;
	default:	goto yy61;
	}
yy63:
	yych = *++in->cur;
	switch (yych) {
	case 'o':	goto yy72;
	default:	goto yy47;
	}
yy64:
	++in->cur;
	switch ((yych = *in->cur)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy65;
	}
yy65:
#line 82 "request_scanners.re"
	{ printf("nc");              continue; }
#line 492 "request_scanners.c"
yy66:
	yych = *++in->cur;
	switch (yych) {
	case 'n':	goto yy73;
	default:	goto yy47;
	}
yy67:
	yych = *++in->cur;
	switch (yych) {
	case 'p':	goto yy74;
	default:	goto yy47;
	}
yy68:
	yych = *++in->cur;
	switch (yych) {
	case 's':	goto yy76;
	default:	goto yy47;
	}
yy69:
	yych = *++in->cur;
	switch (yych) {
	case 'i':	goto yy77;
	default:	goto yy47;
	}
yy70:
	yych = *++in->cur;
	switch (yych) {
	case 'e':	goto yy79;
	default:	goto yy47;
	}
yy71:
	++in->cur;
	yych = *in->cur;
	switch (yych) {
	case '/':	goto yy35;
	default:	goto yy59;
	}
yy72:
	yych = *++in->cur;
	switch (yych) {
	case 'n':	goto yy80;
	default:	goto yy47;
	}
yy73:
	yych = *++in->cur;
	switch (yych) {
	case 'c':	goto yy81;
	default:	goto yy47;
	}
yy74:
	++in->cur;
	switch ((yych = *in->cur)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy75;
	}
yy75:
#line 84 "request_scanners.re"
	{ printf("qop");              continue; }
#line 613 "request_scanners.c"
yy76:
	yych = *++in->cur;
	switch (yych) {
	case 'p':	goto yy82;
	default:	goto yy47;
	}
yy77:
	++in->cur;
	switch ((yych = *in->cur)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy78;
	}
yy78:
#line 86 "request_scanners.re"
	{ printf("uri");              continue; }
#line 691 "request_scanners.c"
yy79:
	yych = *++in->cur;
	switch (yych) {
	case 'r':	goto yy83;
	default:	goto yy47;
	}
yy80:
	yych = *++in->cur;
	switch (yych) {
	case 'c':	goto yy84;
	default:	goto yy47;
	}
yy81:
	yych = *++in->cur;
	switch (yych) {
	case 'e':	goto yy85;
	default:	goto yy47;
	}
yy82:
	yych = *++in->cur;
	switch (yych) {
	case 'o':	goto yy87;
	default:	goto yy47;
	}
yy83:
	yych = *++in->cur;
	switch (yych) {
	case 'n':	goto yy88;
	default:	goto yy47;
	}
yy84:
	yych = *++in->cur;
	switch (yych) {
	case 'e':	goto yy89;
	default:	goto yy47;
	}
yy85:
	++in->cur;
	switch ((yych = *in->cur)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy86;
	}
yy86:
#line 81 "request_scanners.re"
	{ printf("nonce");              continue; }
#line 799 "request_scanners.c"
yy87:
	yych = *++in->cur;
	switch (yych) {
	case 'n':	goto yy91;
	default:	goto yy47;
	}
yy88:
	yych = *++in->cur;
	switch (yych) {
	case 'a':	goto yy92;
	default:	goto yy47;
	}
yy89:
	++in->cur;
	switch ((yych = *in->cur)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy90;
	}
yy90:
#line 83 "request_scanners.re"
	{ printf("cnonce");              continue; }
#line 883 "request_scanners.c"
yy91:
	yych = *++in->cur;
	switch (yych) {
	case 's':	goto yy93;
	default:	goto yy47;
	}
yy92:
	yych = *++in->cur;
	switch (yych) {
	case 'm':	goto yy94;
	default:	goto yy47;
	}
yy93:
	yych = *++in->cur;
	switch (yych) {
	case 'e':	goto yy95;
	default:	goto yy47;
	}
yy94:
	yych = *++in->cur;
	switch (yych) {
	case 'e':	goto yy97;
	default:	goto yy47;
	}
yy95:
	++in->cur;
	switch ((yych = *in->cur)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy96;
	}
yy96:
#line 87 "request_scanners.re"
	{ printf("response");              continue; }
#line 979 "request_scanners.c"
yy97:
	++in->cur;
	switch ((yych = *in->cur)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy46;
	default:	goto yy98;
	}
yy98:
#line 85 "request_scanners.re"
	{ printf("username");              continue; }
#line 1051 "request_scanners.c"
}
#line 96 "request_scanners.re"

    }
}
