/* Generated by re2c 0.16 on Sat Aug 27 18:53:28 2016 */
#line 1 "request_scanners.re"

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <string.h>

#include "Zend/zend_API.h"
#include "Zend/zend_smart_str.h"

/* Adapted from http://re2c.org/examples/example_07.html */
/* @see: https://secure.php.net/manual/en/features.http-auth.php */
/* @see: https://www.w3.org/Protocols/rfc2616/rfc2616-sec2.html */
/* @see: https://en.wikipedia.org/wiki/Digest_access_authentication */

#define YYCTYPE char

enum scanner_token_type {
    TOKEN_END = 0,
    TOKEN_ERROR,
    TOKEN_UNKNOWN,
    TOKEN_WHITESPACE,
    TOKEN_STRING,
    TOKEN_EQUALS,
    TOKEN_COMMA,
    TOKEN_ID
};

struct scanner_input {
    unsigned char * buf;
    unsigned char * tok;
    unsigned char * cur;
    unsigned char * mar;
    unsigned char * lim;
};

struct scanner_token {
    enum scanner_token_type type;
    const unsigned char * yytext;
    size_t yyleng;
};

static zend_string *strip_slashes(unsigned char *str, size_t len)
{
    register char * pos = str;
    register char * end = str + len;
    smart_str buf = {0};
    smart_str_alloc(&buf, len, 0);
    for(; pos != end; pos++ ) {
        if( *pos != '\\' ) {
            smart_str_appendc_ex(&buf, *pos, 0);
        }
    }
    return buf.s;
}

static inline void token1(struct scanner_token *tok, enum scanner_token_type type,  const unsigned char * yytext, size_t yyleng)
{
    tok->type = type;
    tok->yytext = yytext;
    tok->yyleng = yyleng;
}

static struct scanner_token lex_quoted_str(struct scanner_input *in, unsigned char q)
{
    struct scanner_token tok = {0};
    const unsigned char * start = in->cur;

    unsigned char u = q;
    for (;;) {
        in->tok = in->cur;
        
#line 77 "request_scanners.c"
{
	YYCTYPE yych;
	yych = *in->cur;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\\':	goto yy6;
	default:	goto yy4;
	}
yy2:
	++in->cur;
#line 79 "request_scanners.re"
	{ token1(&tok, TOKEN_ERROR, "", 0); return tok; }
#line 90 "request_scanners.c"
yy4:
	++in->cur;
yy5:
#line 80 "request_scanners.re"
	{ u = *in->tok; if (u == q) break; continue; }
#line 96 "request_scanners.c"
yy6:
	yych = *++in->cur;
	switch (yych) {
	case '\n':	goto yy5;
	default:	goto yy7;
	}
yy7:
	++in->cur;
#line 81 "request_scanners.re"
	{ u = *(in->cur - 1); }
#line 107 "request_scanners.c"
}
#line 82 "request_scanners.re"

    }
    token1(&tok, TOKEN_STRING, start, in->tok - start);
    return tok;
}

static struct scanner_token lex_digest_auth(struct scanner_input *in, const char *str, size_t len)
{
    struct scanner_token tok = {0};

    for (;;) {
        in->tok = in->cur;
        
#line 123 "request_scanners.c"
{
	YYCTYPE yych;
	yych = *in->cur;
	switch (yych) {
	case 0x00:	goto yy11;
	case '\t':
	case '\n':
	case '\v':
	case '\r':
	case ' ':	goto yy15;
	case '"':	goto yy17;
	case '\'':	goto yy19;
	case ',':	goto yy20;
	case '-':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy22;
	case '=':	goto yy25;
	default:	goto yy13;
	}
yy11:
	++in->cur;
#line 103 "request_scanners.re"
	{ tok.type = TOKEN_END; return tok; }
#line 208 "request_scanners.c"
yy13:
	++in->cur;
#line 102 "request_scanners.re"
	{ tok.type = TOKEN_UNKNOWN; return tok; }
#line 213 "request_scanners.c"
yy15:
	++in->cur;
#line 106 "request_scanners.re"
	{ continue; tok.type = TOKEN_WHITESPACE; return tok; }
#line 218 "request_scanners.c"
yy17:
	++in->cur;
yy18:
#line 109 "request_scanners.re"
	{ tok = lex_quoted_str(in, *(in->cur - 1)); return tok; }
#line 224 "request_scanners.c"
yy19:
	yych = *++in->cur;
	switch (yych) {
	case '\'':	goto yy27;
	default:	goto yy18;
	}
yy20:
	++in->cur;
#line 113 "request_scanners.re"
	{ token1(&tok, TOKEN_COMMA, ",", 1); return tok; }
#line 235 "request_scanners.c"
yy22:
	++in->cur;
	yych = *in->cur;
	switch (yych) {
	case '-':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy22;
	default:	goto yy24;
	}
yy24:
#line 117 "request_scanners.re"
	{ token1(&tok, TOKEN_ID, in->tok, in->cur - in->tok); return tok; }
#line 309 "request_scanners.c"
yy25:
	++in->cur;
#line 112 "request_scanners.re"
	{ token1(&tok, TOKEN_EQUALS, "=", 1); return tok; }
#line 314 "request_scanners.c"
yy27:
	++in->cur;
#line 110 "request_scanners.re"
	{ token1(&tok, TOKEN_STRING, "", 0); return tok; }
#line 319 "request_scanners.c"
}
#line 118 "request_scanners.re"

    }
}

void php_request_parse_digest_auth(zval *return_value, const char *str, size_t len)
{
    struct scanner_input in = {
        str,
        str,
        str,
        0,
        str + len
    };
    struct scanner_token tok = {0};
    struct scanner_token left;
    struct scanner_token right;
    zval need = {0};
    zend_string *value;

    // Build need array
    array_init(&need);
    add_assoc_bool_ex(&need, ZEND_STRL("nonce"), 1);
    add_assoc_bool_ex(&need, ZEND_STRL("nc"), 1);
    add_assoc_bool_ex(&need, ZEND_STRL("cnonce"), 1);
    add_assoc_bool_ex(&need, ZEND_STRL("qop"), 1);
    add_assoc_bool_ex(&need, ZEND_STRL("username"), 1);
    add_assoc_bool_ex(&need, ZEND_STRL("uri"), 1);
    add_assoc_bool_ex(&need, ZEND_STRL("response"), 1);

    // Parse digest auth
    array_init(return_value);
    for(;;) {
        // Read ID
        tok = lex_digest_auth(&in, str, len);
        if( tok.type != TOKEN_ID ) {
            break;
        }
        left = tok;

        // Read equals
        tok = lex_digest_auth(&in, str, len);
        if( tok.type != TOKEN_EQUALS ) {
            break;
        }

        // Read ID | string
        tok = lex_digest_auth(&in, str, len);
        if( tok.type != TOKEN_ID && tok.type != TOKEN_STRING ) {
            break;
        }
        right = tok;

        // Save KV pair
        if( right.type == TOKEN_STRING ) {
            value = strip_slashes(right.yytext, right.yyleng);
        } else {
            value = zend_string_init(right.yytext, right.yyleng, 0);
        }
        add_assoc_str_ex(return_value, left.yytext, left.yyleng, value);
        zend_hash_str_del(Z_ARRVAL_P(&need), left.yytext, left.yyleng);

        // Read comma | end
        tok = lex_digest_auth(&in, str, len);
        if( tok.type != TOKEN_COMMA ) {
            break;
        }
    };

    if( zend_array_count(Z_ARRVAL_P(&need)) > 0 ) {
        // blow result away if invalid
        ZVAL_NULL(return_value);
    } else {
        convert_to_object(return_value);
    }

    zval_dtor(&need);
}
